/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Category = IDL.Variant({
  'it' : IDL.Null,
  'mason' : IDL.Null,
  'plumber' : IDL.Null,
  'other' : IDL.Null,
  'electrician' : IDL.Null,
  'cleaner' : IDL.Null,
  'driver' : IDL.Null,
  'carpenter' : IDL.Null,
});
export const User = IDL.Record({
  'id' : IDL.Principal,
  'portfolio' : IDL.Vec(ExternalBlob),
  'isPremium' : IDL.Bool,
  'profession' : IDL.Text,
  'fullName' : IDL.Text,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'isProvider' : IDL.Bool,
  'category' : IDL.Opt(Category),
  'phoneNumber' : IDL.Text,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'portfolio' : IDL.Vec(ExternalBlob),
  'isPremium' : IDL.Bool,
  'profession' : IDL.Text,
  'fullName' : IDL.Text,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'isProvider' : IDL.Bool,
  'category' : IDL.Opt(Category),
  'phoneNumber' : IDL.Text,
  'location' : IDL.Text,
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'content' : IDL.Text,
  'receiverId' : IDL.Principal,
  'timestamp' : Time,
  'threadId' : IDL.Text,
  'senderId' : IDL.Principal,
});
export const Review = IDL.Record({
  'provider' : IDL.Principal,
  'comment' : IDL.Text,
  'stars' : IDL.Nat,
  'timestamp' : Time,
  'reviewer' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMessageThread' : IDL.Func([IDL.Text], [], []),
  'getAllProviders' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessageThreads' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'getReviews' : IDL.Func([IDL.Principal], [IDL.Vec(Review)], ['query']),
  'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Opt(Category)],
      [],
      [],
    ),
  'removePortfolioFile' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProvidersByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(User)],
      ['query'],
    ),
  'searchProvidersByProfession' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(User)],
      ['query'],
    ),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [], []),
  'submitReview' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
  'updateAvatar' : IDL.Func([IDL.Text], [], []),
  'uploadPortfolioFile' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Category = IDL.Variant({
    'it' : IDL.Null,
    'mason' : IDL.Null,
    'plumber' : IDL.Null,
    'other' : IDL.Null,
    'electrician' : IDL.Null,
    'cleaner' : IDL.Null,
    'driver' : IDL.Null,
    'carpenter' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : IDL.Principal,
    'portfolio' : IDL.Vec(ExternalBlob),
    'isPremium' : IDL.Bool,
    'profession' : IDL.Text,
    'fullName' : IDL.Text,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'isProvider' : IDL.Bool,
    'category' : IDL.Opt(Category),
    'phoneNumber' : IDL.Text,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'portfolio' : IDL.Vec(ExternalBlob),
    'isPremium' : IDL.Bool,
    'profession' : IDL.Text,
    'fullName' : IDL.Text,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'isProvider' : IDL.Bool,
    'category' : IDL.Opt(Category),
    'phoneNumber' : IDL.Text,
    'location' : IDL.Text,
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'content' : IDL.Text,
    'receiverId' : IDL.Principal,
    'timestamp' : Time,
    'threadId' : IDL.Text,
    'senderId' : IDL.Principal,
  });
  const Review = IDL.Record({
    'provider' : IDL.Principal,
    'comment' : IDL.Text,
    'stars' : IDL.Nat,
    'timestamp' : Time,
    'reviewer' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMessageThread' : IDL.Func([IDL.Text], [], []),
    'getAllProviders' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessageThreads' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'getReviews' : IDL.Func([IDL.Principal], [IDL.Vec(Review)], ['query']),
    'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Opt(Category)],
        [],
        [],
      ),
    'removePortfolioFile' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProvidersByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(User)],
        ['query'],
      ),
    'searchProvidersByProfession' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(User)],
        ['query'],
      ),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [], []),
    'submitReview' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
    'updateAvatar' : IDL.Func([IDL.Text], [], []),
    'uploadPortfolioFile' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };