/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'it' : null } |
  { 'mason' : null } |
  { 'plumber' : null } |
  { 'other' : null } |
  { 'electrician' : null } |
  { 'cleaner' : null } |
  { 'driver' : null } |
  { 'carpenter' : null };
export type ExternalBlob = Uint8Array;
export interface Message {
  'content' : string,
  'receiverId' : Principal,
  'timestamp' : Time,
  'threadId' : string,
  'senderId' : Principal,
}
export interface Review {
  'provider' : Principal,
  'comment' : string,
  'stars' : bigint,
  'timestamp' : Time,
  'reviewer' : Principal,
}
export type Time = bigint;
export interface User {
  'id' : Principal,
  'portfolio' : Array<ExternalBlob>,
  'isPremium' : boolean,
  'profession' : string,
  'fullName' : string,
  'avatarUrl' : [] | [string],
  'isProvider' : boolean,
  'category' : [] | [Category],
  'phoneNumber' : string,
  'location' : string,
}
export interface UserProfile {
  'portfolio' : Array<ExternalBlob>,
  'isPremium' : boolean,
  'profession' : string,
  'fullName' : string,
  'avatarUrl' : [] | [string],
  'isProvider' : boolean,
  'category' : [] | [Category],
  'phoneNumber' : string,
  'location' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMessageThread' : ActorMethod<[string], undefined>,
  'getAllProviders' : ActorMethod<[], Array<User>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessageThreads' : ActorMethod<[], Array<string>>,
  'getMessages' : ActorMethod<[string], Array<Message>>,
  'getReviews' : ActorMethod<[Principal], Array<Review>>,
  'getUser' : ActorMethod<[Principal], [] | [User]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<
    [string, string, string, string, boolean, [] | [Category]],
    undefined
  >,
  'removePortfolioFile' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProvidersByCategory' : ActorMethod<[Category], Array<User>>,
  'searchProvidersByProfession' : ActorMethod<[string], Array<User>>,
  'sendMessage' : ActorMethod<[Principal, string, string], undefined>,
  'submitReview' : ActorMethod<[Principal, bigint, string], undefined>,
  'updateAvatar' : ActorMethod<[string], undefined>,
  'uploadPortfolioFile' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];